### ISSUE TITLE
Add in European Union Membership outermost regions

### ISSUE THREAD

**Issue by DmitriyLendel** [countries/countries#399]
https://en.wikipedia.org/wiki/Member_state_of_the_European_Union

**Comment by rposborne** [comment]
@DmitriyLendel could I have a bit more context about what you want to be added?

**Comment by DmitriyLendel** [comment]
I want to in the method in_eu? displayed Outermost regions (Madeira, Azores, Mayotte etc)
>ISO3166::Country.find_country_by_name('mayotte').in_eu?
=> false
> ISO3166::Country.find_country_by_name('martinique').in_eu?
=> false

**Comment by rposborne** [comment]
@DmitriyLendel Is there a separate classification for the outermost region? As the EU website does not list the countries you have mentioned as in the EU? I found this page that adds some clarity.  I assume we need to track these classifications separately? Or do they still constitute "in the EU"?

**Comment by kkumler** [comment]
Spending a few minutes trying to understand what is going on there...
According to http://ec.europa.eu/regional_policy/sources/policy/themes/outermost-regions/pdf/rup_2017/rup_eu_lands_world_en.pdf, it seems that the 9 Outermost Regions are part of the EU, because they are part of a member country (so `in_eu?` would be true).
However, the overseas countries and territories (OCT) would not count as "in the EU."
It's a bit strange with these countries having their own country code in ISO as well as being a subdivision of another country. e.g. Mayotte ISO3166-1 'YT', and 'FR-YT' under France in ISO3166-2
Hopefully this helps!

**Comment by pmor** [comment]
This was addressed by #794 and #796
