### ISSUE TITLE
'states' method for united states returns several subdivisions that are not states

### ISSUE THREAD

**Issue by dkennell** [countries/countries#575]
When I run `ISO3166::Country['us'].states` I get back a hash with 60 keys, which is 10 more than the 50 states the U.S. is commonly known to have. The issue is that the output includes not just states, but insular areas and U.S. military mail codes as well. I can understand why these would show up in a call to `.subdivisions`, but I don't think they have a place in `.states.` For context, I'm trying to use `countries` to build a select tag that allows a user in the U.S. to select their state. My first thought is that there could be more methods, such as `.military_mail_codes` and `.insular_areas` I'd be happy to implement them, unless you have another solution in mind.

Also this is my first time ever trying to do open source, so if I'm doing this wrong please have mercy 😅

**Comment by stephen-apto** [comment]
@rposborne are you the maintainer for this repo now? i'm seeing above issue as well. [ISO's website for the US](https://www.iso.org/obp/ui/#iso:code:3166:US) shows a subdivision category (state, district, etc) that the ISO3166 struct doesn't seem to have. should this be added? just trying to do a filter for US states and found it challenging

**Comment by rposborne** [comment]
Yea that's certainly a bit surprising. 

It seems reasonable to track this category.  `.states` should be 50 for sure, the sixty-nifty United States just doesn't have the same ring to it. 

I am more than open to a PR addressing this.  Though I think this would need to classify that a breaking change.

**Comment by xiaoronglv** [comment]
is there any update on this issue?

**Comment by pmor** [comment]
Nothing new. I took a quick look at the code, and the underlying issue is that `states` is just an alias of `subdivisions` `https://github.com/countries/countries/blob/835e41c625cc9851f1fbc47bf75c7ce1883849c5/lib/countries/country.rb#L71`, so the 60 or so results correspond to the `ISO 3166-2` subdivisions of the US.

Separating these two methods to have different behaviours requires us to have some way to differentiate between the 50 states and the 'non-state' subdivisions, in some way that makes sense not just for the US, but for any other country that has more than one type of subdivisions.

At this point, we don't have any information in this gem on what the ISO 3166-2 subdivisions mean for different countries. Eg, for the US it's the 50 states, 1 district and 6 outlying areas, while PT has 18 districts and 2 autonomous regions, and there's probably several other designations for different types of subdivisions.

**Comment by pmor** [comment]
PR #720 removes the Armed Forces subdivisions that are not part of ISO data. The remaining subdivisions are all in ISO.

The subdivision object is in need of some refactoring to deal with countries that have different types/tiers of subdivisions at the ISO3166-2 level.

**Comment by pmor** [comment]
Addressed with #758 and `Country#subdivisions_of_types(types)`
