### ISSUE TITLE
Vietnam is not loading properly

### ISSUE THREAD

**Issue by Buildzzz** [countries/countries#621]
Hi, thanks for creating this GEM.

We are using it for our project and the country "Vietnam" is coming out as "Viet Nam" with an erroneous space and capital letter. 

Can you provide a quick fix for this?

**Comment by pmor** [comment]
@Buildzzz This gem follows ISO naming, and "Viet Nam" is the name adopted by ISO (https://www.iso.org/obp/ui/#iso:code:3166:VN).

The translated names, however, tend to use the more common names instead of the ISO, eg: `ISO3166::Country[:VN].translations['en']` has "Vietnam" as the English name, instead of the ISO, so maybe that would work for you?

**Comment by Buildzzz** [comment]
Thanks that's helpful!
ᐧ
