### ISSUE TITLE
Translations for United States of America

### ISSUE THREAD

**Issue by glenpike** [countries/countries#687]
The 'en' locale has a translation for the US as 'United States', where I believe this should be 'United States of America' as per 

https://github.com/countries/countries/pull/384

See in lib/countries/cache/locales/en.json file

**Comment by pmor** [comment]
The translated country names JSON files are generated from [i18n_data](https://github.com/grosser/i18n_data), which uses data from [pkg-isocodes](https://salsa.debian.org/iso-codes-team/iso-codes). 

That data set does not use ISO country names, but instead what you could call "common" country names, such as 'United States' instead of 'United States of America' or 'United Kingdom' instead of 'United Kingdom of Great Britain and Northern Ireland'

In this gem, you have both the ISO names and the translated "common" names, please see https://github.com/countries/countries#names--translations for the methods corresponding to each
