### ISSUE TITLE
Subdivisions without a name

### ISSUE THREAD

**Issue by florianroesler** [countries/countries#695]
While using the subdivisions in a prototype, I realized that many subdivisions do not have a name but carry an English translation. To me that is unexpected behavior as I would have expected the name to be a "default" translation.

It seems like this is the case for around 20% of all subdivisions (1253 of 5844), based on the following code:

`ISO3166::Country.countries.map { |country| country.subdivisions.values.select { |division| division.name.nil? && division.translations.key?('en') } }.flatten`

An example of such a record is the one for "American Samoa":

```
#<struct ISO3166::Subdivision
 name=nil,
 code=nil,
 unofficial_names=nil,
 geo={"latitude"=>-14.270972, "longitude"=>-170.132217, "min_latitude"=>-14.7217608, "min_longitude"=>-171.0076904, "max_latitude"=>-13.4056506, "max_longitude"=>-169.2059326},
 translations={"en"=>"American Samoa"},
 comments=nil>
```

From an implementation perspective I can easily fallback to the English translation. I just think that having an empty name is something that many will find unexpected when using this gem.

What do you think?

**Comment by pmor** [comment]
Something to thing about, for sure. 

Subdivisions are currently just a struct, so that kind of fallback would likely require turning them into a proper object
Issue #580 also requires changes to how subdivision data is loaded, so I feel like this is something to look into as part of a broader refactor of Subdivision code.

As for the specific example of American Samoa, that is bad data on the corresponding YAML file, and I'll be pushing a fix soon

**Comment by pmor** [comment]
This should no longer being an issue with the data fixes and the added sanity checks.
