### ISSUE TITLE
GDPR covered countries

### ISSUE THREAD

**Issue by dsantosmerino** [countries/countries#696]
To support different behaviors in our platform, we'd like to easily identify when a country is covered by the GDPR. I think that it could fit well here, as we have also `#in_eu?` or `#in_esm?`, for example.

Do you think it could make sense to add something like `#GDPR_covered?`? If that's the case I can create a small PR adding it.

**Comment by pmor** [comment]
I'm not a lawyer, but I'm fairly confident that the GDPR applies to EU and EEA members (https://en.wikipedia.org/wiki/General_Data_Protection_Regulation). Since all EU members are also EEA members, the existing `#in_eea?` attribute indicates GDPR coverage.

If that is the case, then I'm not keen on adding another method. (The `#in_eea?`, `#in_esm?` and `#in_eu?` attributes do have small differences between them).

Any thoughts on this @rposborne, @hexorx?
