### ISSUE TITLE
find_country_by_iso_short_name returns nil

### ISSUE THREAD

**Issue by nhinze** [countries/countries#744]
Any idea why Country.find_country_by_iso_short_name returns nil but Country.find_country_by_name works just fine in 4.2.2?

iMac$ irb
```
2.6.9 :001 > require 'countries/global'
 => true 
2.6.9 :002 > c    = ISO3166::Country.find_country_by_iso_short_name('united states')
 => nil 
2.6.9 :003 > c    = ISO3166::Country.find_country_by_name('united states')
/Users/username/.rvm/gems/ruby-2.6.9@mcw-rails-52/gems/countries-4.2.2/lib/countries/country/class_methods.rb:101: warning: DEPRECATION WARNING: 'find_by_name' and 'find_*_by_name' methods are deprecated, please refer to the README file for more information on this change.
 => #<ISO3166::Country:0x00007fc68b3778b0....
```

**Comment by pmor** [comment]
According to https://www.iso.org/obp/ui/#iso:code:3166:US, the "short name" is `United States of America`, while the "long name" is `The United States of America`, so it's expected. 

`Country.find_country_by_name` currently searches in both iso name fields, plus the translations, that use "common names" as well as the `unofficial_names` attribute.

The method was deprecated because of the confusion between different "kinds" of country names, and will likely be renamed to something clearer.

**Comment by nhinze** [comment]
Thanks. What is the correct replacement for find_country_by_name then?

You may want to update the README as it shows this example under "Attribute Based Methods":

`c    = ISO3166::Country.find_country_by_iso_short_name('united states')`

**Comment by pmor** [comment]
Oh, well spotted!

There's no replacement yet, but there will be in the next release, sometime in April.

**Comment by pmor** [comment]
@nhinze The replacement method will be `#find_country_by_any_name`.It keeps the same behaviour of searching over the official and unofficial names as well as the translated names.

It will be part of the 5.0 release that will happen in the next few days.
