### ISSUE TITLE
Possible to delete subdivisions' info of some particular cases

### ISSUE THREAD

**Issue by colmexdev** [countries/countries#751]
Hello there.

   During my tests with this awesome gem, I found that there are some particular cases where info of subdivisions is redundant or inaccurate. For example, Mexico has 32 states and there are listed 33 in reference to "Distrito Federal" (which is now renamed to "Ciudad de México"). This comes to an incorrect display in a select where user can specify the state where it belongs to.

   Furthermore, I found that France holds some countries listed as subdivisions (like Wallis et Futuna), so my question is: Is there a way to delete that undesired info on load?

   Thank you in advance!

**Comment by pmor** [comment]
Hi,

At this time, it's not possible. We've had have some similar issues reported, because ISO data includes different types of subdivisions, but we don't yet have a way to filter subdivision types.

As for the update to "Distrito Federal", thanks for mentioning that, I'll be updating the Mexico data soon.
