### ISSUE TITLE
5.1 breaking change I18nData

### ISSUE THREAD

**Issue by espen** [countries/countries#761]
I see that 5.0 states that I18nData is no longer in use: ["we use data originally sourced from pkg-isocodes, via the i18n_data gem"](https://github.com/countries/countries/blob/master/UPGRADE.md). However this doesn't seem to be the case before 5.1: https://github.com/countries/countries/commit/76736c815379ffdd6a1b3b3be8af35579a443e7c#diff-eb1b3f8e0e5f87f28536ab3b59e04ceec2c8a614de813238d0fd35644e692eec

After 5.1 I am unable to specify language name using `I18nData.languages` even though the upgrade document says "The methods to access translated names have not been changed.". It now results in `uninitialized constant I18nData`

1. Perhaps document this modified behaviour?
2. Is there a way to set the language names after 5.1? I was previously using `I18nData.languages['ES'] = 'Spanish'`

**Comment by pmor** [comment]
`I18nData.languages` is part of the `i18n_data` gem, not part of this one, so I'm not quite sure what your use-case is for setting language names with regards to this gem.

In any event, if you add `i18n_data` to your Gemfile, you should be able to use it as before, it's just that the `countries` gem no longer depends on it to provide translated country names.

**Comment by espen** [comment]
Sure. Sorry I assumed this gem loaded language translations, I see now that it was only country translations.

btw, curious why the dependency was dropped. Isn't it beter to rely on a source that would be updated instead of having the translations hard coded in this gem? Country names can be politically sensitive as well.

**Comment by pmor** [comment]
The issue is that `i18n_data` has been getting some incorrect translations from `pkg-isocodes` due to the way the locale files are parsed to get the translations. 

At this time, I think we have a fairly solid set of translations so it's easier to do small corrections as needed, rather than having to maintain a growing list of translation overrides and sanity checking everything each time `i18n_data` releases an update.
