### ISSUE TITLE
Taiwan labeled as Province of China

### ISSUE THREAD

**Issue by lisbethpurrucker** [countries/countries#823]
Taiwan should not have the "Province of China" addition to it, it is apparently a very controversial political term created by the chinese media. My users feel uncomfortable to label themselves as part of China though.

**Comment by pmor** [comment]
This gem has long followed the rule of using ISO names, and as per https://www.iso.org/obp/ui/#iso:code:3166:TW, `Taiwan (Province of China)` is the ISO short name for Taiwan.

I suggest using the `common_name` attribute, since for most cases, that is the country name you'd expect to see in a dropdown box, for instance.

Eg:, For the UK, the ISO name is `United Kingdom of Great Britain and Northern Ireland`, and the `common_name` is just `United Kingdom`.
