### ISSUE TITLE
I suggest changing the source also to my repo where I keep the updated list from iso.org

### ISSUE THREAD

**Issue by detrin** [countries/countries#851]
I prepared a repo where you can use the CLI to fetch the newest ISO 3166 list or use the countries.json file. https://github.com/detrin/download-iso3166-list

**Comment by pmor** [comment]
Thanks, but we don't use an external list of countries. This repo contains years of collected data that includes a lot of information that is not part of the ISO data set.

Changes to ISO data set are quite rare: Since I've been maintaining the gem, only a few subdivision changes have happened, and 2 changes to official country names.
